#!/usr/bin/env bash

export LC_ALL=C
export LANG=C

# ANSI Colors
RESET="\033[0m"

# Regular Colors
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
MAGENTA="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"

# Bold
BOLD_BLACK="\033[1;30m"
BOLD_RED="\033[1;31m"
BOLD_GREEN="\033[1;32m"
BOLD_YELLOW="\033[1;33m"
BOLD_BLUE="\033[1;34m"
BOLD_MAGENTA="\033[1;35m"
BOLD_CYAN="\033[1;36m"
BOLD_WHITE="\033[1;37m"

function CHECK_PKG() {
	target_pkg="$@"

	if ! grep "\bjpkg\b$" <<< "$target_pkg"; then
		printf '%b' "\e${BOLD_RED}The package must be .jpkg!\e${RESET}\n"
		return 1
	fi

	if grep -qE "[[:space:]]+" <<< "$target_pkg"; then
		printf '%b' "\e${BOLD_RED}Invalid package name!\e${RESET}\n"
		return 1
	fi
}

function CREATE_PKG() {
	target_pkg="$1"

	if [[ "$VERBOSE" = "1" ]]; then
		if tar -cvzf "../${target_pkg}" .; then
			printf '%b' "\e${BOLD_GREEN}Package created in ../${target_pkg}\e${RESET}\n"
			return 0
		else
			printf '%b' "\e${BOLD_RED}Error on package create!\e${RESET}\n"
			exit 1
		fi
	else
		if tar -czf "../${target_pkg}" .; then
			printf '%b' "\e${BOLD_GREEN}Package created in ../${target_pkg}\e${RESET}\n"
			return 0
		else
			printf '%b' "\e${BOLD_RED}Error on package create!\e${RESET}\n"
			exit 1
		fi
	fi
}

function USAGE() {
	cat <<EOF
Parameters:
	create|-c	:	Create a package
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		create|-c)
			CMD=$1
			shift
		;;
		verbose|-v)
			VERBOSE=1
			shift
		;;
		*.jpkg)
			PKG=$1
			shift
		;;
		*|-h) USAGE
			exit 0
		;;
	esac
done

case "$CMD" in
	create|-c)
		shift
		if [[ -z "$CMD" ]]; then
			printf '%b' "\e${BOLD_WHITE}Missing target package name!\e${RESET}\n"
			exit 1
		fi

		CHECK_PKG "$PKG" || exit 1
		CREATE_PKG "$PKG"
	;;
esac
